# -*- coding: utf-8 -*-
"""BarutaHeartDiseasePredictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2sGPspTGfk9ZdNOCyrXEKyWy2dPuxIu
"""

!pip install Boruta

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from boruta import BorutaPy
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
from matplotlib import style

data = pd.read_csv('heart.csv')

X = data.drop('target', axis=1)
y = data['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
rf = RandomForestClassifier(n_estimators=100, n_jobs=-1, class_weight='balanced')
boruta_selector = BorutaPy(rf, n_estimators='auto', verbose=2)

np.int=np.int64
np.float=np.float64
np.bool=np.bool_

boruta_selector.fit(np.array(X_train), np.array(y_train))
selected_features = X.columns[boruta_selector.support_]
print("Selected Features:", selected_features)
X_train_selected = X_train[selected_features]
X_test_selected = X_test[selected_features]

rf.fit(X_train_selected, y_train)

predictions = rf.predict(X_test_selected)

from sklearn.metrics import accuracy_score, classification_report

accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, predictions))

r2_test = metrics.r2_score(y_test , predictions)
print('R squared value: ', r2_test)

train_data_prediction = rf.predict(X_train_selected)

r2_train = metrics.r2_score(y_train , train_data_prediction)
print('R squared value: ', r2_train)

input_data = (52,1,300,382,300,0,.7,2,0,3)

# changing input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
print(input_data_reshaped)
prediction = rf.predict(input_data_reshaped)
print(prediction)

import pickle
import joblib
filename = 'BarutaHeartDiseasePredictor.pkl'
joblib.dump(rf , filename)